### ISSUE TITLE
LoadPack(zip, password)工作不正常

### ISSUE THREAD

**Issue by Airtnp** [Xiliusha/LuaSTG-EX-Plus#1]
minizip的unzip.c需要注释掉 #define NOUNCRYPT 否则对所有非null的unzOpenCurrentFilePassword都直接返回UNZ_PARAERRO（-102）

对unicode（特指中文）密码加密的zip，部分软件（好压）将gbk编码作为passwd，而lua层返回utf8编码

**Comment by Xiliusha** [comment]
现在已经转为使用libzip库，这个问题已经不存在了。
